name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Google Cloud SDK
      run: |
        gcloud config set app/cloud_build_timeout 1200
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Google Cloud App Engine
      run: gcloud app deploy --quiet
